version: "3.9"
services:
  web:
    build:
      context: ../..
      dockerfile: operation/Docker/Dockerfile
    ports:
      - "3000:80"
    image: 613622767668.dkr.ecr.us-east-2.amazonaws.com/brain-task-app
    container_name: braintask-web
